### ISSUE TITLE
Launch args added to "Target" field instead of "Launch Options" field

### ISSUE THREAD

**Issue by rkr87** [doZennn/steam-rom-manager#307] opened 2022-05-17 20:10 UTC
I've noticed that the launch arguments provided in SRM are saved to the "Target" field in the Steam shortcuts created instead of the "Options" field. This doesn't cause any problems from a Steam perspective, I can still launch all of the games fine - however, it does cause issues with other 3rd party applications that parse the shortcuts.vdf file.

Would it be possible to get the option to store the launch arguments in the "Launch Options" field in the shortcuts.vdf file?

**Comment by cbartondock** [comment] 2022-05-17 23:01
Do you have append args to executable ticked? Because if so this is the intended behavior. All you have to do is untick it.

**Comment by rkr87** [comment] 2022-05-18 00:13
Well, that's embarrassing. Yeah, that sorted my issue.
Thanks!

**Comment by cbartondock** [comment] 2022-05-18 01:53
Happens to the best of us :) and SRM's UI is a little bit all over the place. Closing.

**Closed as completed by cbartondock** 2022-05-18 01:53 UTC
