### ISSUE TITLE
`launchOptions` not in steam launch option but at the end of target in manual mode

### ISSUE THREAD

**Issue by swhoro** [doZennn/steam-rom-manager#625] opened 2023-12-21 09:38 UTC
I want a game's launch option in steam is filled by `launchOptions` field in manifest.json, what should I do?

I find a related issue: https://github.com/SteamGridDB/steam-rom-manager/issues/307, but I do not find `append args to executable` option.

**Comment by HazardousBackup** [comment] 2023-12-24 22:03
I can't say for sure because I'm not familiar enough with the codebase yet but maybe `config.executable.appendArgsToExecutable` is supposed to be `parsedConfig.appendArgsToExecutable` here:
https://github.com/SteamGridDB/steam-rom-manager/blob/ed718710bdc2cb14527f801b82afb8c8353efb40/src/lib/file-parser.ts#L415

Some quick and dirty testing on my part shows the change moves `launchOptions` in a Manual parser to the Steam `Launch Options` field instead of appending it to the executable and the `append args to executable` option, that is only available on ROM/Glob parsers, still works.

**Comment by cbartondock** [comment] 2024-04-18 15:36
The issue is actually that the manual parser doesn't have a toggle for this at the moment, I think the right way to do it (in the spirit of the manual parser) is to just add a field to the JSON file that determines this behavior (whether the launchOptions appear in the target or separately in steam).

**Comment by cbartondock** [comment] 2024-04-18 16:04
![Screenshot 2024-04-18 120330](https://github.com/SteamGridDB/steam-rom-manager/assets/4482454/ae4bf6d5-896b-4e63-8c22-bd6248b65c6e)
Will be fixed in the next update.

**Closed as completed by cbartondock** 2024-04-18 16:04 UTC
