### ISSUE TITLE
CLI throws exception - tries opening file node_modules/yargs/locales/en_US.json

### ISSUE THREAD

**Issue by KirstenZa** [doZennn/steam-rom-manager#628] opened 2024-01-05 00:06 UTC
I get the error below when trying to use the CLI.
The application does not really start doing anything.

I tried options "--help", "list" and "add".
I tried version 2.4.0, version 2.4.12, version 2.4.17
I tried the portable version and I installed via MSI.
I am using Windows 10.

![FileError](https://github.com/SteamGridDB/steam-rom-manager/assets/25637976/5f0f631a-db1e-41a0-afeb-39c257f63f30)

**Comment by cbartondock** [comment] 2024-04-27 21:06
Portable CLI is definitely broken, specifically it can't print anything do to a limitation in electron for portable apps. I am unable to reproduce with MSI (my copy of SRM is installed via MSI and everything works fine in the CLI). Does this also happen if you install via setup executable?

**Comment by KirstenZa** [comment] 2024-04-28 17:33
Yes, it happened also when installing.
I really needed a working solution, so I just build it by myself. It also works now for me. However, after three months and tons of work, I just do not remember if I did some nasty things... sorry!

**Comment by cbartondock** [comment] 2024-04-28 17:58
Okay I am going to close this in that case!

**Closed as completed by cbartondock** 2024-04-28 17:58 UTC
