### ISSUE TITLE
[REQUEST] filter by artist

### ISSUE THREAD

**Issue by f4mrfaux** [doZennn/steam-rom-manager#642] opened 2024-03-25 03:40 UTC
"Filter by artist"

- **Feature information**
allow users to filter for / offer priority to art created by spesific users. castcoder does excellent work, imo

- **Additional context**
an ability to add an artist to the glob.
castcoders art all has bumpers on the top that show the platform of the game. it is consistent and easily read.
conversely, if you were a "man of culture" as it were you could auto get all your lewd waifu boxart done by your favorite rule34 artist or whatever.

**Comment by cbartondock** [comment] 2024-05-06 13:49
Duplicate of [issue 434](https://github.com/SteamGridDB/steam-rom-manager/issues/434)

**Closed as completed by cbartondock** 2024-05-06 13:49 UTC
Labels: enhancement
