### ISSUE TITLE
Steam Link Hardware issue with UWP and EA Games

### ISSUE THREAD

**Issue by oOoSeVeNoOo** [doZennn/steam-rom-manager#553] opened 2023-05-10 17:47 UTC
Hi, 
Hoping you can help. 

Issue = Importing games (UWP and EA Games) to steam works fine, However, when using Steam Link Hardware to play these games, the main game window does not keep the focus, and therefore leaves the steam window active, which then controllers will not work with it, even if i Alt-Tab to the correct screen, controllers still don't work. 
This happens even when just loading on main PC

Ive tried, many things lets call them, ie like below, but generally have no idea what im doing, im getting old now.
"C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe" -windowStyle hidden -NoProfile -ExecutionPolicy Bypass -Command "&Start-Process \"origin2://game/launch/?offerIds=1028663&action=launch&silent=true\"; sleep 5; $wshell = New-Object -ComObject WScript.Shell; $wshell.AppActivate('O:\Origin games\AWayOut\Haze1\Binaries\Win64')"

Tried using main .exe file etc 

This used to happen with Epic games, then a few updates ago, it just started working.

Any help or guidance  or future updates that fix this kind of issue would be awesome.
Please ask any questions if you need more info
Thank you for any help given

**Comment by kencinder** [comment] 2023-12-08 01:27
SRM doesn't run anything, it adds shortcuts and nothing more.
Someone on the Discord may be able to help, but this is not a bug and out of scope here.

**Closed as completed by kencinder** 2023-12-08 01:27 UTC

**Comment by renk02** [comment] 2024-01-20 17:01
> Hi, Hoping you can help.
> 
> Issue = Importing games (UWP and EA Games) to steam works fine, However, when using Steam Link Hardware to play these games, the main game window does not keep the focus, and therefore leaves the steam window active, which then controllers will not work with it, even if i Alt-Tab to the correct screen, controllers still don't work. This happens even when just loading on main PC
> 
> Ive tried, many things lets call them, ie like below, but generally have no idea what im doing, im getting old now. "C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe" -windowStyle hidden -NoProfile -ExecutionPolicy Bypass -Command "&Start-Process "origin2://game/launch/?offerIds=1028663&action=launch&silent=true"; sleep 5; $wshell = New-Object -ComObject WScript.Shell; $wshell.AppActivate('O:\Origin games\AWayOut\Haze1\Binaries\Win64')"
> 
> Tried using main .exe file etc
> 
> This used to happen with Epic games, then a few updates ago, it just started working.
> 
> Any help or guidance or future updates that fix this kind of issue would be awesome. Please ask any questions if you need more info Thank you for any help given


Hello, my friend! I'm facing the same issue, and up to now, I haven't found a solution. I tried the same procedures above, but without success. Does any developer have a solution?

I noticed that games played through Uplay work perfectly. I would like games via UWP, Epic, and EA Desktop to work the same way.
