### ISSUE TITLE
Parser "failed to match" when roms in root of drive.

### ISSUE THREAD

**Issue by andyjf0** [doZennn/steam-rom-manager#580] opened 2023-07-15 07:02 UTC
Attempting to run SRM with Xenia Xbox 360 preset.
User glob is: ${title}@(.iso|.ISO)

My parser log:

Custom variables file has been downloaded.
New config presets have been downloaded.
Testing "Microsoft XBox 360 - Xenia" parser (SRM version - 2.4.17 Non-Portable).
Operating system is "Windows 10"
 
Parser ID: 16894040213439562

Found 1 available user account(s):
  XXXXXXXX-XXXXX-XXX (steamID64: 76561197962088125, accountID: 1822397)
 
Number of Titles: 0
 
Failed to match:
[1/2]: D:\Red Dead Redemption GOTY.iso
[2/2]: D:\Red Dead Redemption - Undead Nightmare (USA, Europe) (En,Fr,De,Es,It).iso
 
Parser test is completed.

**Comment by andyjf0** [comment] 2023-07-15 07:21
Resolved.
Seems SRM doesn't like ROMs being in a drive's root directory.
Moving the ROMs to folder D:\360 ROMs has it working perfectly!

**Comment by kencinder** [comment] 2023-12-08 00:48
Confirming this is oddly enough, an issue.

Tested with a rom in the root of a drive, have the same issue.

**Comment by cbartondock** [comment] 2024-04-25 15:46
This issue is caused by an issue in [node-glob](https://github.com/isaacs/node-glob/issues/583)

Waiting on a response from them, I may do a hacky fix in the meantime but it would be better fixed upstream.

**Comment by cbartondock** [comment] 2024-04-25 16:07
Fixed in master with a hack, will remove if it is fixed in node-glob.

**Closed as completed by cbartondock** 2024-04-25 16:07 UTC
Labels: bug
