### ISSUE TITLE
[REQUEST] Allow for use of `~` or `$HOME` in parsers on Linux

### ISSUE THREAD

**Issue by fpiesche** [doZennn/steam-rom-manager#699] opened 2024-08-08 00:16 UTC
- **Feature information**
For the sake of portability between different machines or sharing of the same parsers between multiple users on the same system, it'd be extremely useful if on Linux or macOS, `$HOME` or `~` could be used in parsers' executable or ROM path fields. This would allow e.g. two separate users on the same system to use the same `userConfigurations.json` (say, in a system-wide Flatpak installation of SRM) but have different ROM directories in their home directory (as long as they use the same names for the same systems).

- **Additional context**
Currently, SRM will report executables or ROM paths starting with `$HOME` or `~` as invalid:
![image](https://github.com/user-attachments/assets/8673d502-ad91-45e3-8943-2cc860ac6184)

**Comment by cbartondock** [comment] 2024-10-18 22:07
Closing as duplicate of [the path parsing issue](https://github.com/SteamGridDB/steam-rom-manager/issues/375). The solution would be the same.

**Closed as completed by cbartondock** 2024-10-18 22:07 UTC
