### ISSUE TITLE
Identify and apply recommended community controller layouts for Non-Steam Games

### ISSUE THREAD

**Issue by rkr87** [doZennn/steam-rom-manager#316] opened 2022-05-21 10:45 UTC
I have a number of Non-Steam games from Epic/GOG installed as Non-Steam Games that exist on Steam. For some reason Steam can't seem to find community controller layouts for these games even though they're saved with the same title as the Steam game. I'm not sure if this is possible, but it would be good if SRM could identify recommended community controller layouts on Steam and apply them to non-Steam Games.

NOTE: I just want to apologise for bombarding with enhancement requests, just getting started with SRM (which is by far the best tool I've found for managing non-Steam games) and had a few ideas that I think could take it to the next level.

**Comment by cbartondock** [comment] 2022-05-21 12:20
Closing as a duplicate of https://github.com/SteamGridDB/steam-rom-manager/issues/13

Community configs would be through the presets.

**Closed as completed by cbartondock** 2022-05-21 12:20 UTC
