### ISSUE TITLE
Creating categories in the Steam app (outside of SRM) resets all collections to "0"

### ISSUE THREAD

**Issue by 03bgood** [doZennn/steam-rom-manager#430] opened 2023-01-04 21:23 UTC
The categories for ROM Manager seems to work fine, however if I try to create one via the Steam app on my Steam Deck, I'll reset every non-Steam game category to 0 once I boot into Gaming Mode. If I delete the categories made by the Steam app, the issue goes away and the categories no longer reset to "0". I think this is an issue with either ROM Manager or the Steam app. I'll get an error saying "Failure - Could not save collection [Category name]" if I try to create one via the Steam app (Gaming or Desktop Mode) and that also resets everything to 0. So it's definaly some kind of major bug.

**Comment by jasonmbrown** [comment] 2023-02-12 20:57
The same thing seems to happen if you modify a category using the steam app. It will reset all collections not made in Steam to 0 except the one you modified. In my case I had to remove and correct a bunch of Yuzu Games manually (Since it adds all the DLC and Updates to the folders).

**Comment by cbartondock** [comment] 2023-04-03 17:06
I am unable to reproduce this. Could you dm me on the discord @lontanadascienza so we can look at your files

**Comment by cbartondock** [comment] 2023-05-03 03:01
Closing for lack of comment, but category management should be better in the next release.

**Closed as completed** 2023-05-03 03:01 UTC
